name: Daily Image Crawler

on:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC 16:00 (北京时间凌晨0:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - name: Configure Git global settings
      run: |
        git config --global http.postBuffer 524288000
        git config --global core.compression 9
        git config --global http.lowSpeedLimit 1000
        git config --global http.lowSpeedTime 300
    
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 1  # 只获取最新的提交
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz pillow
        
    - name: Configure Git for commit
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        
    - name: Run crawler
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python crawler.py
      
    - name: Commit and Push
      run: |
        # 确保我们在正确的分支上
        git checkout main
        
        # 尝试提交更改
        git add .
        git status
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add images for $(date +'%Y%m%d')"
          
          # 使用多次重试的方式推送
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempting to push changes (attempt $(($RETRY_COUNT + 1)))"
            
            if git push origin main; then
              echo "Successfully pushed changes"
              break
            else
              RETRY_COUNT=$(($RETRY_COUNT + 1))
              
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "Push failed, pulling latest changes and retrying..."
                git pull --rebase origin main
                sleep 5
              else
                echo "Failed to push after $MAX_RETRIES attempts"
                exit 1
              fi
            fi
          done
        fi 