name: Daily Image Crawler

on:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC 16:00 (北京时间凌晨0:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
    
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz pillow
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
    - name: Run crawler
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python crawler.py
      
    - name: Push changes
      run: |
        git add .
        git commit -m "Add images for $(date +'%Y%m%d')" || echo "No changes to commit"
        git push 