name: Daily Image Crawler

on:
  schedule:
    - cron: '0 1 * * *'  # UTC 1:00 AM (北京时间 9:00 AM)
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write        # 仅设置必要的写入权限

jobs:
  crawl-images:
    name: Crawl Yesterday's Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4 Pillow
          fi
      
      - name: Run image crawler
        run: |
          echo "开始运行图片爬虫..."
          # 确保目标文件夹存在
          YESTERDAY=$(date -u -d "yesterday" +"%Y%m%d")
          mkdir -p "$YESTERDAY"
          
          # 运行爬虫脚本并捕获错误
          if ! python crawler.py; then
            echo "爬虫脚本执行失败"
            exit 1
          fi
          echo "爬虫运行完成"
      
      - name: Verify crawled images
        run: |
          YESTERDAY=$(date -u -d "yesterday" +"%Y%m%d")
          echo "检查昨天的图片文件夹: $YESTERDAY"
          
          if [ -d "$YESTERDAY" ]; then
            echo "文件夹存在，内容如下："
            ls -lh "$YESTERDAY"
            
            # 检查图片数量
            IMAGE_COUNT=$(ls -1 "$YESTERDAY"/*.jpg 2>/dev/null | wc -l)
            echo "共抓取到 $IMAGE_COUNT 张图片"
            
            if [ $IMAGE_COUNT -eq 0 ]; then
              echo "警告：没有找到任何图片"
              exit 1  # 如果没有图片，视为失败
            fi
          else
            echo "错误：文件夹不存在"
            exit 1
          fi
      
      - name: Commit and push
        if: success()  # 只在之前的步骤都成功时执行
        run: |
          YESTERDAY=$(date -u -d "yesterday" +"%Y%m%d")
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [ -d "$YESTERDAY" ]; then
            git add "$YESTERDAY"
            
            if git diff --staged --quiet; then
              echo "没有新的更改需要提交"
            else
              git commit -m "Add images for $(date -u -d "yesterday" +"%Y-%m-%d")"
              git push
              echo "更改已提交并推送"
            fi
          fi
